# src/main/resources/application.yml
spring:
  application:
    name: inventory-management
  
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/inventory_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:}
    driver-class-name: org.postgresql.DDriver
    hikari:
      maximum-pool-size: 10
  
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    show-sql: true

server:
  port: ${PORT:8080}